bounds: &world
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
center:
  - 3.4018
  - 47.8511
  - 18
format: png8
interactivity: false
minzoom: 6
maxzoom: 20

scale: 1
metatile: 8
name: volta-cartocss
description: ''
attribution: 'data source: ORE/Enedis/RTE'

# Various parts to be included later on
_parts:
  extents: &extents
    extent: *world
    srs-name: "3857"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  extents84: &extents84
    extent: *world
    srs-name: "WGS84"
    srs: "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
  db: &db
    type: "postgis"
    dbname: "osm"
    host: "localhost"
    user: "fr"
    password: m4d31nfr4nc3
    geometry_field: "wkb_geometry"
    extent: *world
    srid: 4326
    asynchronous_request: 'true'
    max_async_connection: '4'


Stylesheet:
  - style.mss
  - volta.mss

Layer:
  # Surfacique
  - id: rte_enceintes_de_poste
    properties:
      minzoom: 14
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            wkb_geometry,
            nom_poste
          FROM
            rte_enceintes_de_poste
        ) as rte_enceintes_de_poste

  - id: ore_distributeurs
    <<: *extents
    properties:
      minzoom: 14
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            way,
            grd_elec,
            commune
          FROM
            osm_communes c
          JOIN
            ore_distributeurs d
          ON (insee=code_insee_commune)
        ) as ore_distributeurs
      geometry_field: way

  # Linéaire
  - id: volta_lignes_lz
    properties:
      minzoom: 11
      maxzoom: 13
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            *
          FROM
            volta_lignes
          WHERE ht and not underground
        ) as volta_lignes_lz
      geometry_field: geom

  - id: volta_lignes
    properties:
      cache-features: on
      minzoom: 14
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            *,
            ST_Length(geom)/!pixel_width! as pixels
          FROM
            volta_lignes
        ) as volta_lignes
      geometry_field: geom

  - id: rte_lignes_souterrainnes
    properties:
      cache-features: on
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            ST_LineMerge(ST_Collect(wkb_geometry)) as wkb_geometry,
            etat,
            regexp_replace(format(E'%s / %s x %s\n%s\n%s\n%s',nom_ligne, nombre_circuit, tension, nom_ouvrage_2, nom_ouvrage_3, nom_ouvrage_4),e'(LIAISON |\n+$)','','g') as libelle
          FROM
            rte_lignes_souterraines
          WHERE
            wkb_geometry && !bbox!
          GROUP BY 2,3
        ) as rte_lignes_souterraines

  - id: rte_lignes_aeriennes
    properties:
      cache-features: on
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            ST_LineMerge(ST_Collect(wkb_geometry)) as wkb_geometry,
            etat,
            regexp_replace(format(E'%s / %s x %s\n%s\n%s\n%s\n%s',nom_ligne, nombre_circuit, tension, nom_ouvrage_2, nom_ouvrage_3, nom_ouvrage_4, nom_ouvrage_5),e'(LIAISON |\n+$)','','g') as libelle
          FROM
            rte_lignes_aeriennes
          WHERE
            wkb_geometry && !bbox!
          GROUP BY 2,3
        ) as rte_lignes_aeriennes

  # Ponctuel
  - id: volta_postes
    properties:
      minzoom: 14
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            *
          FROM
            volta_postes
        ) as volta_postes
      geometry_field: geom

  - id: volta_pole_hta
    properties:
      minzoom: 18
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            (st_dump(st_points(geom))).geom as pole
          FROM
            volta_lignes
          WHERE geom && !bbox!
          AND ht and not underground
        ) as volta_pole_hta
      geometry_field: pole

  - id: enedis_pole
    properties:
      cache-features: on
      minzoom: 16
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            *
          FROM
            enedis_pole
        ) as enedis_pole

  - id: rte_pylones
    properties:
      cache-features: on
      minzoom: 14
    <<: *extents84
    Datasource:
      <<: *db
      table: >-
        (
          SELECT
            wkb_geometry,
            numero_pylone,
            case when hauteur_pylone>0 then
              format(e'%s\n%sm', numero_pylone, hauteur_pylone)
            else
              numero_pylone::text
            end as libelle
          FROM
            rte_pylones
        ) as rte_pylones
      geometry_field: wkb_geometry

